spring:
  profiles:
    active: 'local'

application:
  endpoint: 'https://shotbow.net/serverList.json'
  max-interval-days: 366
  gamemodes:
    - 'all'
    - 'minez'
    - 'smash'
    - 'annihilation'
    - 'dbv'
    - 'slaughter'
    - 'wir'
    - 'gg'
    - 'lobby'
    - 'minerproblems'
    - 'warband'
    - 'mta'
