name: CD

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Tag'
        required: true

env:
  CONTAINER_NAME: shotbow-playercount-api
  IMAGE_NAME: shotbow-playercount-api

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Environment variables
            IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag }}"
            CONTAINER_NAME="${{ env.CONTAINER_NAME }}"
            VIRTUAL_HOST="${{ secrets.VIRTUAL_HOST }}"
            DATABASE_URL="${{ secrets.DATABASE_URL }}"
            DATABASE_USERNAME="${{ secrets.DATABASE_USERNAME }}"
            DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}"
            
            ls
            cat docker-compose.yml

            # Stop and remove old instance
            docker-compose down

            # Start new instance
            docker-compose up -d
